### ISSUE TITLE
Option to prioritize GTA on launch

### ISSUE THREAD

**Issue by justinkruit** [moffa13/GTA-V-Launcher#2]
There are some ways to make GTA run better by giving it a high priority in Windows Task Manager. Maybe it's a good idea to add a setting to the launcher to give GTA that priority after like a minute (to let the game boot first)?

**Comment by moffa13** [comment]
Why after a minute and not right after the GTA5.exe process is created ?

**Comment by moffa13** [comment]
Ok this will be added in the next release :)
