### ISSUE TITLE
Error: "Please start Steam, log in and try again".

### ISSUE THREAD

**Issue by WSLUser** [moffa13/GTA-V-Launcher#4]
Please fix the detection mechanism for when Steam is running.

**Comment by moffa13** [comment]
Done, thank you for submitting the issue.

**Comment by WSLUser** [comment]
I'll give it another try if you publish a new zip with the change

**Comment by moffa13** [comment]
Hello

You can already find the file on gta5-mods or in the release section on github.


-------- Message d'origine --------
De : WSLUser <notifications@github.com>
Date : 30/06/20 20:24 (GMT+01:00)
À : moffa13/GTA-V-Launcher <GTA-V-Launcher@noreply.github.com>
Cc : moffa13 <moffajeremy@outlook.com>, State change <state_change@noreply.github.com>
Objet : Re: [moffa13/GTA-V-Launcher] Error: "Please start Steam, log in and try again". (#4)


I'll give it another try if you publish a new zip with the change
